export enum ArtifactKind {
  TOPIC_RESEARCH = 'TOPIC_RESEARCH',
  CREATIVE_OPTION = 'CREATIVE_OPTION',
  TIMELINE = 'TIMELINE',
  RENDER_OUTPUT = 'RENDER_OUTPUT',
  THUMBNAIL = 'THUMBNAIL',
  RELEASE_PACKAGE = 'RELEASE_PACKAGE',
  RUN_REPORT = 'RUN_REPORT',
}
