export enum AgentTaskType {
  TOPIC_RESEARCH = 'TOPIC_RESEARCH',
  CREATIVE_BRIEF = 'CREATIVE_BRIEF',
  TIMELINE_PROPOSAL = 'TIMELINE_PROPOSAL',
  QA_REVIEW = 'QA_REVIEW',
  ANALYTICS_REVIEW = 'ANALYTICS_REVIEW',
}

export enum AgentResultStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
}
