export enum GateType {
  CREATIVE_BRIEF = 'CREATIVE_BRIEF',
  DRAFT_REVIEW = 'DRAFT_REVIEW',
  RELEASE_PACKAGE = 'RELEASE_PACKAGE',
}

export enum GateStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}
